spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?useSSL=false
    username: root
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8080
